package com.tastyelectrons.firestore

import com.tastyelectrons.firestore.external.QueryDocumentSnapshot

actual class QueryDocumentSnapshot(queryDocumentSnapshot: QueryDocumentSnapshot): DocumentSnapshot(queryDocumentSnapshot)